name: PyPi Release

on:
    push:
    pull_request:
    workflow_dispatch:

# based on https://github.com/pypa/gh-action-pypi-publish
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install setuptools
      run: >-
        python -m pip install --user --upgrade setuptools wheel
    - name: Install cython
      run: >-
        python -m pip install --user --upgrade Cython
    - name: Install twine
      run: >-
        python -m pip install --user --upgrade twine
    - name: Build
      run: >-
        python setup.py sdist
    - name: Publish distribution 📦 to PyPI
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      run: >-
        twine upload dist/*
