name: mamonca-testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        python-version: ${{ matrix.python-version }}
        channel-priority: strict
        environment-file: .ci_support/environment.yml

    - name: Install dependencies
      run: conda env update --file .ci_support/environment.yml --name base

    - name: run tests
      shell: bash -l {0}
      run: |
        pip install -e .
        python -m unittest discover tests/

